version: '3'
services:
  coursepicker:
    command: 'gunicorn -b 127.0.0.1:5000 --log-level debug --access-logfile - coursepicker.app:application'
    build:
      context: .
      dockerfile: containers/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./coursepicker:/opt/coursepicker/coursepicker
      - ./conf:/opt/coursepicker/conf
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  test:
    command: pytest test
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - ./:/opt/coursepicker/

  cli:
      command: '/bin/bash'
      build:
        context: .
        dockerfile: containers/Dockerfile
      volumes:
        - ./:/opt/coursepicker/
      depends_on:
        - db
